### ISSUE TITLE
Toggle Switch is transparent when turn on

### ISSUE THREAD

**Issue by whdgmawkd** [nana-4/Flat-Plat#87] opened 2016-11-07 09:42 UTC
Distribution : Debian GNU/Linux stretch/sid 64-bit
Linux 4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux

Desktop environment : GNOME Shell 3.22.1

GTK+ 3 version : 3.22.1

Flat-Plat version : master branch at "a3f3fab006cd30ff819876b501e6ce06513a84b4"

Related application version : gnome-control-center 1:3.22.1-1

Steps to reproduce : On state Toggle switch has no circle and only has it's shadow. or just turn off and turn on again any toggle.

![screenshot from 2016-11-07 18-38-31](https://cloud.githubusercontent.com/assets/6850405/20052922/7d597a30-a519-11e6-9c6d-f4ad1ae7796b.png)

**Comment by Skehmatics** [comment] 2016-11-07 13:43
Are you sure this isn't a duplicate of #82?

**Comment by nana-4** [comment] 2016-11-09 04:30
Yeah, this was a duplicate. But thank you for the report. :)

**Closed by nana-4** 2016-11-09 04:30 UTC

**Comment by whdgmawkd** [comment] 2016-11-09 11:26
Oops! I cant see that issue. Sorry.
