### ISSUE TITLE
Strange border in nautils window

### ISSUE THREAD

**Issue by rollsappletree** [nana-4/Flat-Plat#103] opened 2017-03-02 12:14 UTC
Hi guys!
I just tried the theme and seems gorgeous!

But there is a strange orange border in nautils window:
http://screencloud.net/v/5VriA

it seems very strange to me :smile: 
ps: it only happens with Nautilus window!
how i remove it?

- Flat-Plat version: latest from github
- GTK+ 3 version: dunno!
- Distribution: Ubuntu 16:04
- Desktop environment; Unity
- Related application: Nautilus
- Steps to reproduce: Open Nautilus :smile: 
- Screenshot: http://screencloud.net/v/5VriA

**Comment by nana-4** [comment] 2017-03-02 19:24
Hi, thank you for your bug reporting 😃

I expect you did something like [this article](http://www.omgubuntu.co.uk/2017/02/how-to-enable-nautilus-csd-header-bar-ubuntu), but I had not tried it, so I didn't notice this bug. 😅 

I applied a patch, but I currently don't have _Ubuntu 16.04_. So could you please check if the problem is resolved?

You can try latest one like this:
```
cd /tmp
curl -sL https://github.com/nana-4/Flat-Plat/archive/master.tar.gz | tar xz
cd Flat-Plat-master && sudo ./install.sh
```

**Comment by alexive** [comment] 2017-03-11 18:06
I had the same problem (on ubuntu 16.10) but that patch fixed it! 😃

**Comment by nana-4** [comment] 2017-03-19 10:09
@alexive Thanks for your report. 😃 

It seems to be fixed, so I close this issue.

**Closed by nana-4** 2017-03-19 10:09 UTC
Labels: bug
