### ISSUE TITLE
Checkboxes are solid red and QT programs using qt5-styleplugins are broken.

### ISSUE THREAD

**Issue by The-King-of-Toasters** [nana-4/Flat-Plat#153] opened 2017-09-29 13:05 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Flat-Plat version: _Latest Git_
- GTK+ 3 version: 3.22.21-1
- Distribution: Arch on kernel 4.13
- Desktop environment GNOME Shell 3.24.3
- Related application LibreOffice, Firefox, assorted QT apps
- Steps to reproduce
1. Clone Repo
2. Run `install.sh` as root
3. Set GTK+ Theme and GNOME Shell theme to `Flat-Plat compact`
4. Run affected programs
- Screenshot(s)
![Combined image](https://user-images.githubusercontent.com/9159492/31017038-81881e2a-a56a-11e7-8c47-2734b6abb7f7.png)

**Comment by nana-4** [comment] 2017-09-29 22:02
I can't reproduce this. And it doesn't look like a _vanilla_ `Flat-Plat-compact`. Didn't you install the theme customized by yourself?

**Comment by The-King-of-Toasters** [comment] 2017-09-30 04:50
The only change made is that the shell font is `PreludeWGL` instead of roboto and the titlebars are shortened. Using vanilla shows the same errors.

**Comment by nana-4** [comment] 2017-09-30 05:13
I think you deleted the [`assets/`](https://github.com/nana-4/Flat-Plat/tree/master/src/gtk-3.0/gtk-common/assets) directory.
Please check if `/usr/share/themes/Flat-Plat-compact/gtk-common/assets` directory exists.

**Comment by The-King-of-Toasters** [comment] 2017-09-30 07:19
All the files are accounted for. But I decided to re-download the repo and install again. Looks like my problem is fixed now. Strange, but I probably should've tried that first. Thanks for helping me out anyway @nana-4!
![screenshot from 2017-09-30 17-18-35](https://user-images.githubusercontent.com/9159492/31043680-871faf62-a603-11e7-86a3-eb23a8781ffd.png)

**Comment by nana-4** [comment] 2017-09-30 07:33
I'm glad it was solved anyway. :)
Closing.

**Closed by nana-4** 2017-09-30 07:33 UTC
Labels: cannot reproduce
