### ISSUE TITLE
Dark Title Bars

### ISSUE THREAD

**Issue by michael-rapp** [nana-4/Flat-Plat#56] opened 2016-07-23 11:42 UTC
I am using the Flat-Plat theme on my Arch Linux system using the AUR package https://aur.archlinux.org/packages/flatplat-theme-git/. I recently updated the package and it caused the title bars of all applications (also those that use the light theme variant) to become dark. You can see this in the attached screenshot. This really confuses me, because the screenshots on this Github page still show light title bars. Is this change intended?

![screenshot from 2016-07-23 13-39-15](https://cloud.githubusercontent.com/assets/6638695/17077733/2b642a0a-50db-11e6-93f0-5c60e705979c.png)

**Comment by Skehmatics** [comment] 2016-07-23 15:55
See 5006ca5 and issue #51

TL;DR: yes, it was intended. nana-4 hasn't updated the photos yet as the color scheme isn't set in stone yet.

**Comment by michael-rapp** [comment] 2016-07-23 15:59
Ok. Will there still be a light variant? I would really appreciate this.

**Comment by El-Zipo** [comment] 2016-07-23 23:57
I still like the light variant

**Comment by hickop** [comment] 2016-07-30 11:27
+1 for keeping a version with light titlebars.

@michael-rapp you could use flat-plat from AUR (not the git one), it's based on latest release which does not include dark titlebars.

**Comment by michael-rapp** [comment] 2016-07-31 01:46
@hickop Thank you, I am already using the flat-plat package from AUR. But once the new color scheme is officially released this will not work anymore.

**Comment by El-Zipo** [comment] 2016-08-03 01:14
@nana-4 
I'm still like the old flat-plat theme (white color theme)
I like to develop that white color theme.
I need your permission and your help in the future.

Regards.

**Comment by nana-4** [comment] 2016-08-07 04:03
Hmm, I might be available the light title bars version again.

@El-Zipo Theme is under GPL, so you can fork it, of course!

**Comment by El-Zipo** [comment] 2016-08-07 06:20
Thank you @nana-4

**Comment by michael-rapp** [comment] 2016-08-21 14:10
@El-Zipo Did you already create a fork? I couldn't find anything.

**Comment by sharifzadesina** [comment] 2016-08-21 15:17
@nana-4 
I don't know why you really removed opacity of top bar...
I don't know why you really changed title bars color to dark...
I still love the old theme, we could have dark title bars in _global dark_ version...

**Comment by El-Zipo** [comment] 2016-08-21 23:52
@michael-rapp 
This is it.
[https://www.gnome-look.org/p/1150374/](url)

But in these days, I'm using new flat-plat thene :smile:

**Comment by El-Zipo** [comment] 2016-08-21 23:53
https://www.gnome-look.org/p/1150374/
This is it @michael-rapp

**Comment by sharifzadesina** [comment] 2016-08-23 09:56
@El-Zipo Upload this on github dude, I will help you in maintenance.

**Comment by nana-4** [comment] 2016-08-26 13:42
@sharifzadesina 
Sorry for the late reply.
There is some reason, but biggest reason is that I wanted to be more Material Design to this theme.
In Material design guidelines, most apps have dark (or colored) title bar.
Btw, I'm going to release a version with light title bars. :)

**Comment by El-Zipo** [comment] 2016-08-26 23:39
I'm waiting for the light version. Thanks @nana-4

**Comment by Skehmatics** [comment] 2016-09-08 19:09
@michael-rapp @USBA @sharifzadesina 
Until nana-4 makes an official light version, I added a "light-title-bar" branch to my fork. :}

https://github.com/Skehmatics/Flat-Plat/tree/light-title-bars

**Comment by USBA** [comment] 2016-09-09 07:08
@Skehmatics 
Wow! Great.
This is my flat-plat with light title bars,
![89c7e053e1b76fb322bb4f864b4ea809eeff](https://cloud.githubusercontent.com/assets/19838220/18378370/381e5c32-768a-11e6-97cb-bd91643952cd.png)
https://www.gnome-look.org/p/1150374/

**Comment by USBA** [comment] 2016-09-09 07:20
@Skehmatics 
Text in the menu bar is nearly invisible.
Change the font color to black.

![screenshot from 2016-09-09 12-45-39](https://cloud.githubusercontent.com/assets/19838220/18378658/d41bcf7e-768b-11e6-811f-2c8f8c9a1f5c.png)

**Comment by Skehmatics** [comment] 2016-09-10 00:17
@USBA fixed in 263455d23e70671b979028be8b04500654f0bdd2
For future issues regarding my fork itself, submit an issue *on* my fork. Its unofficial, so submitting them here is probably an annoyance for nana-4

**Comment by curvi** [comment] 2016-11-06 21:49
Considering it is "just" a downgrade or reset to and old version, can I ask which channel the light version will be available (own repo or something else)? And if there is an estimated time of arival?
Keep up the good work! Cheers!

**Comment by nana-4** [comment] 2016-11-09 06:00
Finally, light title bar version is now available. You can get it from the top page.
And I apologize for the release being delayed.

**Comment by nana-4** [comment] 2016-11-09 06:01
@curvi Sorry for the delay. It is now available.

**Closed by nana-4** 2016-11-09 06:00 UTC
Labels: enhancement

**Comment by curvi** [comment] 2016-11-09 21:17
Thank you so much! No need to be sorry, this is the single most well-developed theme i ever saw.

It's decent and not too fancy - just my style. So thank you very much for all your effort and know, that it is all (every detail) very much appreciated!

Cheers, keep it coming
curvi
